events {}

http {
    server {
        listen 80;
        server_name localhost;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Serve the HTML Frontend
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Route API requests to the Python Microservices
        location /api/chal1/ { proxy_pass http://chal1_none:5000/; }
        location /api/chal2/ { proxy_pass http://chal2_brute:5000/; }
        location /api/chal3/ { proxy_pass http://chal3_kid:5000/; }
        location /api/chal4/ { proxy_pass http://chal4_json_serial:5000/; }
        location /api/chal5/ { proxy_pass http://chal5_alg_confusion:5000/; }
        location /api/chal6/ { proxy_pass http://chal6_jku:5000/; }
    }
}