events {}

http {
    server {
        listen 80;
        server_name localhost;

        # Standardizing headers for the backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        location /chal1/ {
            proxy_pass http://chal1_none:5000/;
        }

        location /chal2/ {
            proxy_pass http://chal2_brute:5000/;
        }

        location /chal3/ {
            proxy_pass http://chal3_kid:5000/;
        }

        location /chal4/ {
            proxy_pass http://chal4_json_serial:5000/;
        }

        location /chal5/ {
            proxy_pass http://chal5_alg_confusion:5000/;
        }

        location /chal6/ {
            proxy_pass http://chal6_jku:5000/;
        }
    }
}